### ISSUE TITLE
problème dans l ordre de déclaration des constructeurs "wrong number of arguments"

### ISSUE THREAD

**Issue by ben5962** [ben5962/variablestableauxboucles#1]
junit.framework.AssertionFailedError: dans le fichier ExerciceTableaux6_10Somme2Tableauxlors de l appel du constructeur, oubli d appel du setter correspondant au getter getEnnonce_exo la valeur obtenue était: pas la bonne chaine expected:<true> but was:<false>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:174)
	at junit.framework.TestCase.assertEquals(TestCase.java:333)
	at variablestableauxboucles.Test_Avancement.test_tous_les_exos_ont_un_ennonce(Test_Avancement.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

en l appelant directement depuis MainMainexercices ca donne:
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at variablestableauxboucles.MainObjetMethodeRemplissage.InstancierTousExos(MainObjetMethodeRemplissage.java:26)
	at variablestableauxboucles.MainObjetRemplirListeExosFromFileSystem.InstancierTousExos(MainObjetRemplirListeExosFromFileSystem.java:1)
	at variablestableauxboucles.MainBDD.getConteneurExercices(MainBDD.java:56)
	at variablestableauxboucles.MainMainExercices.main(MainMainExercices.java:17)

**Comment by ben5962** [comment]
it's a question of constructor signature ordre:
putting 
- constructor with no args in #1 and 
- constructor with args in #2....#n everything fits. i post it.
